### ISSUE TITLE
zip_list

### ISSUE THREAD

**Issue by altor** [derniercri/orchestra#12]
- [ ] insertion dans une liste triée
- [ ] recherche

**Comment by xvw** [comment]
Cette issue peut être fermée ? (tu abandonnes les Zippers ?)

**Comment by Grimimi** [comment]
Je ne suis pas convaincu par l'interface proposée pour les Zip_List. 
Je n'aime pas du tout le fait d'avoir un même niveau d'hiérarchie entre les hauteurs et les contenus. Pourquoi ne pas utiliser deux records ? (Ou alors simplement, une liste indexée "correctement" au lieu de répéter l'implémentation des listes à tailles fixées). 
Je m'interroge aussi sur ... l'intérêt réel d'une liste zippée et pourquoi ne pas simplement admettre qu'un zipper listé est lui même un zipper 2D? 
Sinon j'ai un peu de mal à saisir l'objectif "général" de la bibliothèque ? Elle a une vocation précise ?

**Comment by xvw** [comment]
non.
