### ISSUE TITLE
Coers indépendant

### ISSUE THREAD

**Issue by Grimimi** [derniercri/orchestra#13]
Dans l'implémentation d'une petite page web en Erlang (avec Yaws), je serais très intéressé par Coers, mais beaucoup moins par le reste. Actuellement, j'utilise déjà Jeson (qui implémente une dépendance à Coers). Serait-il possible de l'externaliser de Orchestra ? (Car je n'ai toujours pas bien compris l'intérêt de cette dernière ?)

**Comment by xvw** [comment]
Le projet est continué ici : https://github.com/xvw/coers
Ce n'est pas encore tout à fait fini mais ça corrige déjà la partie "bitstrings" qui avait été complètement oubliée dans la version originale. L'interface est aussi un peu mieux. 
J'ai du l'a réécrire car j'en avais besoin (avec un type résultat un peu plus sexi que l'actuel) pour un projet Erlang que j'ai du reprendre ...
